name: 'aws-spulse'
# version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aws_spulse
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
    driver: local
  cache:
    driver: local
